labels:
  - Mickey Mouse
  - Minnie Mouse
  - Donald Duck
  - Daisy Duck
  - Goofy
  - Pluto
  - Chip
  - Dale
  - Elsa
  - Anna
  - Olaf
  - Rapunzel
  - Moana
  - Stitch
  - Pooh
  - Winnie the Pooh
  - Piglet
  - Tigger
  - Eeyore
  - Simba
  - Nala
  - Pumbaa
  - Timon
  - Buzz
  - Woody
  - Jessie
  - Rex
  - Forky
  - Hamm
  - Alien
  - Mike
  - Sulley
  - Wall-E
  - Eve
  - Nemo
  - Dory
  - Remy
  - Baymax
  - Wreck-It Ralph
  - Vanellope
  - Judy Hopps
  - Nick Wilde
  - Aladdin
  - Jasmine
  - Genie
  - Cinderella
  - Snow White
  - Aurora
  - Ariel
  - Flounder
  - Sebastian
  - Belle
  - Beast
  - Mulan
  - Mushu
  - Tiana
  - Merida
  - Dumbo
  - Bambi
  - Pinocchio
  - Alice
  - Cheshire Cat
  - Mirabel
  - Bruno
  - Luisa
  - Isabela
  - Luca
  - Alberto
  - Asha
  - Hello Kitty
  - My Melody
  - Kuromi
  - Cinnamoroll
  - Pompompurin
  - Pochacco
  - Keroppi
  - Badtz-Maru
  - Hangyodon
  - Little Twin Stars
  - Kiki
  - Lala
  - Marron Cream
  - Usahana
  - Gudetama
  - My Sweet Piano
  - Totoro
  - Medium Totoro
  - Small Totoro
  - Catbus
  - Jiji
  - Jiji the Black Cat
  - No-Face
  - Haku
  - Chihiro
  - Yubaba
  - Ponyo
  - Sosuke
  - Howl
  - Sophie
  - Calcifer
  - San
  - Ashitaka
  - Yakul
  - Kodama
  - Nausicaa
  - Teto
  - Mei
  - Satsuki
  - Arrietty
  - Baron
  - Muta
  - Pikachu
  - Eevee
  - Charmander
  - Charizard
  - Squirtle
  - Blastoise
  - Bulbasaur
  - Snorlax
  - Mew
  - Mewtwo
  - Dragonite
  - Jigglypuff
  - Pichu
  - Lucario
  - Lugia
  - Ho-Oh
  - Growlithe
  - Arcanine
  - Magikarp
  - Gyarados
  - Emolga
  - Psyduck
  - Sylveon
  - Umbreon
  - Glaceon
  - Leafeon
  - Flareon
  - Vaporeon
  - Jolteon
  - Ditto
  - Raichu
  - Shin-chan
  - Shiro
  - Kazama
  - Nene
  - Masao
  - Bo
  - Himawari
  - Misae
  - Hiroshi
  - Ai
  - Action Mask
  - Bonobono
  - Raccoon
  - Porori
  - Chipmunk
  - Araiguma
  - Chiikawa
  - Hachiware
  - Usagi
  - Momonga
  - Kurimanju
  - Pat
  - Mat
  - Pat and Mat
  - Toothless
  - Light Fury
  - Hiccup
  - Astrid
  - Night Fury
  - Stormfly
  - Luffy
  - Zoro
  - Nami
  - Usopp
  - Sanji
  - Chopper
  - Robin
  - Franky
  - Brook
  - Jinbe
  - Law
  - Ace
  - Shanks
  - Sabo
  - Hancock
  - Yamato
  - Bepo
  - Pororo
  - Eddy
  - Poby
  - Crong
  - Petty
  - Harry
  - Rody
  - Tongtong
  - Nyao
  - Mashimaro
  - Miffy
  - Melanie
  - Boris
  - Snuffy
  - Joking Bear
  - Pingu
  - Pinga
  - SpongeBob
  - Patrick
  - Squidward
  - Mr. Krabs
  - Sandy
  - Gary
  - Moomin
  - Snorkmaiden
  - Little My
  - Snufkin
  - Brown
  - Cony
  - Sally
  - Ryan
  - Apeach
  - Muzi
  - Con
  - Neo
  - Frodo
  - Tube
  - Chunsik
  - Peppa Pig
  - George
  - Mario
  - Luigi
  - Princess Peach
  - Toad
  - Yoshi
  - Bowser
  - Kirby
  - Meta Knight
  - Waddle Dee
  - Finn
  - Jake
  - BMO
  - Marceline
  - Snoopy
  - Charlie Brown
  - Woodstock
  - Doraemon
  - Nobita
  - Dorami
  - Anpanman
  - Baikinman
  - Shokupanman
  - Thomas
  - Percy
  - Molang
  - Piu Piu
  - Bbang Bbang
  - Esther Bunny
  - Zanmang Loopy
  - Teletubbies
  - Po
  - Tinky Winky
  - Tayo
  - Rogi
  - Lani
  - Gani
  - Poli
  - Roy
  - Amber
  - Helly
  - Cocomong
  - Heartsping
  - TinyPing
  - Azaping
  - Jett
  - Super Wings
  - Bob
  - Kevin
  - Stuart
  - Minions
  - Goku
  - Vegeta
  - Tanjiro
  - Nezuko
  - Zenitsu
  - Inosuke
  - Rengoku
  - Naruto
  - Sasuke
  - Kakashi
  - Kurama
  - Tata
  - Chimmy
  - Cooky
  - Mang
  - Koya
  - BT21
